"""create weddings table

Revision ID: 159c30463e43
Revises: 
Create Date: 2026-09-15 12:11:31.415579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '159c30463e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_partner', sa.String(length=100), nullable=False),
    sa.Column('second_partner', sa.String(length=100), nullable=False),
    sa.Column('wedding_date', sa.Date(), nullable=False),
    sa.Column('wedding_venue', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weddings_id'), 'weddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weddings_id'), table_name='weddings')
    op.drop_table('weddings')
    # ### end Alembic commands ###
