"""add firebase uid to weddings

Revision ID: 9b28ec2880be
Revises: 159c30463e43
Create Date: 2026-09-18 11:51:18.286976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b28ec2880be'
down_revision: Union[str, Sequence[str], None] = '159c30463e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weddings', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_weddings_firebase_uid'), 'weddings', ['firebase_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weddings_firebase_uid'), table_name='weddings')
    op.drop_column('weddings', 'firebase_uid')
    # ### end Alembic commands ###
