"""add gift id to payments

Revision ID: a6e4cf6f0c2d
Revises: 7dd1e3569966
Create Date: 2026-09-28 12:26:34.159245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6e4cf6f0c2d'
down_revision: Union[str, Sequence[str], None] = '7dd1e3569966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gift_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_gift_id'), 'payments', ['gift_id'], unique=True)
    op.create_foreign_key(None, 'payments', 'gifts', ['gift_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_gift_id'), table_name='payments')
    op.drop_column('payments', 'gift_id')
    # ### end Alembic commands ###
