"""create guests table

Revision ID: d9bbc589bf42
Revises: 9b28ec2880be
Create Date: 2026-09-24 12:15:21.439349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9bbc589bf42'
down_revision: Union[str, Sequence[str], None] = '9b28ec2880be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('rsvp_status', sa.String(length=20), server_default='Pending', nullable=False),
    sa.Column('gift_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_index(op.f('ix_guests_wedding_id'), 'guests', ['wedding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_wedding_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
